// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Portfolio.Infrastructure.Persistence;

#nullable disable

namespace Portfolio.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PortfolioDbContext))]
    partial class PortfolioDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.About", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_published");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<int>("ProjectCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("project_count");

                    b.Property<bool>("ShowContactSection")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("show_contact_section");

                    b.Property<bool>("ShowProjectCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("show_project_count");

                    b.Property<bool>("ShowTechnologyCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("show_technology_count");

                    b.Property<bool>("ShowYearsOfExperience")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("show_years_of_experience");

                    b.Property<int>("TechnologyCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("technology_count");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("YearsOfExperience")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)")
                        .HasDefaultValue(0m)
                        .HasColumnName("years_of_experience");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("abouts", null, t =>
                        {
                            t.HasCheckConstraint("ck_abouts_project_count", "project_count >= 0");

                            t.HasCheckConstraint("ck_abouts_technology_count", "technology_count >= 0");

                            t.HasCheckConstraint("ck_abouts_years_of_experience", "years_of_experience >= 0");
                        });
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.AboutTranslation", b =>
                {
                    b.Property<Guid>("AboutId")
                        .HasColumnType("uuid")
                        .HasColumnName("about_id");

                    b.Property<string>("LocaleCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("locale_code");

                    b.Property<string>("CareerGoal")
                        .HasColumnType("text")
                        .HasColumnName("career_goal");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.HasKey("AboutId", "LocaleCode");

                    b.ToTable("about_translations", null, t =>
                        {
                            t.HasCheckConstraint("ck_about_translations_locale", "locale_code IN ('en', 'vi')");
                        });
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.Certificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CredentialId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("credential_id");

                    b.Property<string>("CredentialUrl")
                        .HasColumnType("text")
                        .HasColumnName("credential_url");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<DateOnly?>("ExpirationDate")
                        .HasColumnType("date")
                        .HasColumnName("expiration_date");

                    b.Property<string>("FileUrl")
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_published");

                    b.Property<DateOnly>("IssuedDate")
                        .HasColumnType("date")
                        .HasColumnName("issued_date");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("issuer");

                    b.Property<bool>("ShowCredentialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("show_credential_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder", "IssuedDate")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_certificates_public_order")
                        .HasFilter("is_published");

                    b.ToTable("certificates", null, t =>
                        {
                            t.HasCheckConstraint("ck_certificates_dates", "expiration_date IS NULL OR expiration_date >= issued_date");

                            t.HasCheckConstraint("ck_certificates_display_order", "display_order >= 0");
                        });
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.CertificateTechnology", b =>
                {
                    b.Property<Guid>("CertificateId")
                        .HasColumnType("uuid")
                        .HasColumnName("certificate_id");

                    b.Property<Guid>("TechnologyId")
                        .HasColumnType("uuid")
                        .HasColumnName("technology_id");

                    b.HasKey("CertificateId", "TechnologyId");

                    b.HasIndex("TechnologyId");

                    b.ToTable("certificate_technologies", (string)null);
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.CertificateTranslation", b =>
                {
                    b.Property<Guid>("CertificateId")
                        .HasColumnType("uuid")
                        .HasColumnName("certificate_id");

                    b.Property<string>("LocaleCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("locale_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("CertificateId", "LocaleCode");

                    b.ToTable("certificate_translations", null, t =>
                        {
                            t.HasCheckConstraint("ck_certificate_translations_locale", "locale_code IN ('en', 'vi')");
                        });
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.ContactMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("IpHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("ip_hash");

                    b.Property<bool>("IsSpam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_spam");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<string>("SenderEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("sender_email");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("sender_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("new")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subject");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id");

                    b.HasIndex("Status", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_contact_messages_admin_filter");

                    b.ToTable("contact_messages", null, t =>
                        {
                            t.HasCheckConstraint("ck_contact_messages_status", "status IN ('new', 'read', 'archived')");
                        });
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.ExperienceHighlight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<Guid>("ExperienceId")
                        .HasColumnType("uuid")
                        .HasColumnName("experience_id");

                    b.Property<string>("HighlightType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("highlight_type");

                    b.Property<string>("LocaleCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("locale_code");

                    b.HasKey("Id");

                    b.HasIndex("ExperienceId", "LocaleCode", "HighlightType", "DisplayOrder")
                        .IsUnique()
                        .HasDatabaseName("idx_experience_highlights_order");

                    b.ToTable("experience_highlights", null, t =>
                        {
                            t.HasCheckConstraint("ck_experience_highlights_display_order", "display_order >= 0");

                            t.HasCheckConstraint("ck_experience_highlights_locale", "locale_code IN ('en', 'vi')");

                            t.HasCheckConstraint("ck_experience_highlights_type", "highlight_type IN ('responsibility', 'achievement')");
                        });
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.ExperienceTechnology", b =>
                {
                    b.Property<Guid>("ExperienceId")
                        .HasColumnType("uuid")
                        .HasColumnName("experience_id");

                    b.Property<Guid>("TechnologyId")
                        .HasColumnType("uuid")
                        .HasColumnName("technology_id");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.HasKey("ExperienceId", "TechnologyId");

                    b.HasIndex("TechnologyId");

                    b.ToTable("experience_technologies", null, t =>
                        {
                            t.HasCheckConstraint("ck_experience_technologies_display_order", "display_order >= 0");
                        });
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.ExperienceTranslation", b =>
                {
                    b.Property<Guid>("ExperienceId")
                        .HasColumnType("uuid")
                        .HasColumnName("experience_id");

                    b.Property<string>("LocaleCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("locale_code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("position");

                    b.HasKey("ExperienceId", "LocaleCode");

                    b.ToTable("experience_translations", null, t =>
                        {
                            t.HasCheckConstraint("ck_experience_translations_locale", "locale_code IN ('en', 'vi')");
                        });
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("AvailableForWork")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("available_for_work");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("full_name");

                    b.Property<string>("HeroImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("hero_image_url");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<bool>("ShowEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("show_email");

                    b.Property<bool>("ShowPhone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("show_phone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.ProfileTranslation", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("LocaleCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("locale_code");

                    b.Property<string>("Availability")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("availability");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<string>("ShortBio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("short_bio");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ProfileId", "LocaleCode");

                    b.ToTable("profile_translations", null, t =>
                        {
                            t.HasCheckConstraint("ck_profile_translations_locale", "locale_code IN ('en', 'vi')");
                        });
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DemoUrl")
                        .HasColumnType("text")
                        .HasColumnName("demo_url");

                    b.Property<string>("DisclosureLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("full")
                        .HasColumnName("disclosure_level");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("InternalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("internal_name");

                    b.Property<bool>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_featured");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_published");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("personal")
                        .HasColumnName("kind");

                    b.Property<string>("RepositoryUrl")
                        .HasColumnType("text")
                        .HasColumnName("repository_url");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)")
                        .HasColumnName("slug");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_url");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Kind", "DisclosureLevel", "IsFeatured", "DisplayOrder")
                        .IsDescending(false, false, true, false)
                        .HasDatabaseName("idx_projects_public_filter_order")
                        .HasFilter("is_published");

                    b.ToTable("projects", null, t =>
                        {
                            t.HasCheckConstraint("ck_projects_dates", "end_date IS NULL OR start_date IS NULL OR end_date >= start_date");

                            t.HasCheckConstraint("ck_projects_disclosure_level", "disclosure_level IN ('full', 'limited')");

                            t.HasCheckConstraint("ck_projects_display_order", "display_order >= 0");

                            t.HasCheckConstraint("ck_projects_kind", "kind IN ('personal', 'professional')");
                        });
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.ProjectHighlight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<string>("LocaleCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("locale_code");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "LocaleCode", "DisplayOrder")
                        .IsUnique()
                        .HasDatabaseName("idx_project_highlights_order");

                    b.ToTable("project_highlights", null, t =>
                        {
                            t.HasCheckConstraint("ck_project_highlights_display_order", "display_order >= 0");

                            t.HasCheckConstraint("ck_project_highlights_locale", "locale_code IN ('en', 'vi')");
                        });
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.ProjectImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "DisplayOrder")
                        .HasDatabaseName("idx_project_images_order");

                    b.ToTable("project_images", null, t =>
                        {
                            t.HasCheckConstraint("ck_project_images_display_order", "display_order >= 0");
                        });
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.ProjectImageTranslation", b =>
                {
                    b.Property<Guid>("ProjectImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_image_id");

                    b.Property<string>("LocaleCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("locale_code");

                    b.Property<string>("AltText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("alt_text");

                    b.HasKey("ProjectImageId", "LocaleCode");

                    b.ToTable("project_image_translations", null, t =>
                        {
                            t.HasCheckConstraint("ck_project_image_translations_locale", "locale_code IN ('en', 'vi')");
                        });
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.ProjectTechnology", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("TechnologyId")
                        .HasColumnType("uuid")
                        .HasColumnName("technology_id");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.HasKey("ProjectId", "TechnologyId");

                    b.HasIndex("TechnologyId");

                    b.ToTable("project_technologies", null, t =>
                        {
                            t.HasCheckConstraint("ck_project_technologies_display_order", "display_order >= 0");
                        });
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.ProjectTranslation", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("LocaleCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("locale_code");

                    b.Property<string>("ClientContext")
                        .HasColumnType("text")
                        .HasColumnName("client_context");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Problem")
                        .HasColumnType("text")
                        .HasColumnName("problem");

                    b.Property<string>("Result")
                        .HasColumnType("text")
                        .HasColumnName("result");

                    b.Property<string>("Role")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("role");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("short_description");

                    b.Property<string>("Solution")
                        .HasColumnType("text")
                        .HasColumnName("solution");

                    b.HasKey("ProjectId", "LocaleCode");

                    b.ToTable("project_translations", null, t =>
                        {
                            t.HasCheckConstraint("ck_project_translations_locale", "locale_code IN ('en', 'vi')");
                        });
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.ResumeFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_published");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language_code");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_file_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("VersionSequence")
                        .HasColumnType("integer")
                        .HasColumnName("version_sequence");

                    b.Property<short>("VersionYear")
                        .HasColumnType("smallint")
                        .HasColumnName("version_year");

                    b.HasKey("Id");

                    b.HasAlternateKey("LanguageCode", "VersionYear", "VersionSequence")
                        .HasName("ak_resumes_language_year_sequence");

                    b.HasIndex("LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("ux_resumes_one_active_per_language")
                        .HasFilter("is_active");

                    b.HasIndex("LanguageCode", "VersionYear", "VersionSequence")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("idx_resumes_public_language_version")
                        .HasFilter("is_published");

                    b.ToTable("resumes", null, t =>
                        {
                            t.HasCheckConstraint("ck_resumes_display_order", "display_order >= 0");

                            t.HasCheckConstraint("ck_resumes_file_size", "file_size > 0");

                            t.HasCheckConstraint("ck_resumes_locale", "language_code IN ('en', 'vi')");

                            t.HasCheckConstraint("ck_resumes_sequence", "version_sequence > 0");

                            t.HasCheckConstraint("ck_resumes_year", "version_year BETWEEN 2000 AND 9999");
                        });
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.ResumeTranslation", b =>
                {
                    b.Property<Guid>("ResumeId")
                        .HasColumnType("uuid")
                        .HasColumnName("resume_id");

                    b.Property<string>("LocaleCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("locale_code");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.HasKey("ResumeId", "LocaleCode");

                    b.ToTable("resume_translations", null, t =>
                        {
                            t.HasCheckConstraint("ck_resume_translations_locale", "locale_code IN ('en', 'vi')");
                        });
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.ResumeVersionCounter", b =>
                {
                    b.Property<string>("LanguageCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language_code");

                    b.Property<short>("VersionYear")
                        .HasColumnType("smallint")
                        .HasColumnName("version_year");

                    b.Property<int>("LastSequence")
                        .HasColumnType("integer")
                        .HasColumnName("last_sequence");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("LanguageCode", "VersionYear");

                    b.ToTable("resume_version_counters", null, t =>
                        {
                            t.HasCheckConstraint("ck_resume_version_counters_locale", "language_code IN ('en', 'vi')");

                            t.HasCheckConstraint("ck_resume_version_counters_sequence", "last_sequence > 0");

                            t.HasCheckConstraint("ck_resume_version_counters_year", "version_year BETWEEN 2000 AND 9999");
                        });
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.SiteSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<JsonDocument>("Value")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("site_settings", (string)null);
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.SkillCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_published");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder")
                        .HasDatabaseName("idx_skill_categories_public_order")
                        .HasFilter("is_published");

                    b.ToTable("skill_categories", null, t =>
                        {
                            t.HasCheckConstraint("ck_skill_categories_display_order", "display_order >= 0");
                        });
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.SkillCategoryTranslation", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("LocaleCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("locale_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("CategoryId", "LocaleCode");

                    b.ToTable("skill_category_translations", null, t =>
                        {
                            t.HasCheckConstraint("ck_skill_category_translations_locale", "locale_code IN ('en', 'vi')");
                        });
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.SocialLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<string>("IconName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("icon_name");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_published");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("platform");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder")
                        .HasDatabaseName("idx_social_links_public_order")
                        .HasFilter("is_published");

                    b.HasIndex("ProfileId", "Platform")
                        .IsUnique();

                    b.ToTable("social_links", null, t =>
                        {
                            t.HasCheckConstraint("ck_social_links_display_order", "display_order >= 0");
                        });
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.Technology", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<string>("IconType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("text")
                        .HasColumnName("icon_type");

                    b.Property<string>("IconValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("icon_value");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_published");

                    b.Property<string>("SkillLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("skill_level");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("YearsOfExperience")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("years_of_experience");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId", "DisplayOrder")
                        .HasDatabaseName("idx_technologies_public_category_order")
                        .HasFilter("is_published");

                    b.ToTable("technologies", null, t =>
                        {
                            t.HasCheckConstraint("ck_technologies_display_order", "display_order >= 0");

                            t.HasCheckConstraint("ck_technologies_icon_type", "icon_type IN ('lucide', 'image', 'text')");

                            t.HasCheckConstraint("ck_technologies_icon_value", "(icon_type = 'text' AND char_length(btrim(icon_value)) BETWEEN 1 AND 6) OR (icon_type = 'lucide' AND char_length(btrim(icon_value)) BETWEEN 1 AND 100 AND icon_value ~ '^[a-z0-9]+(-[a-z0-9]+)*$') OR (icon_type = 'image' AND char_length(btrim(icon_value)) BETWEEN 1 AND 500)");

                            t.HasCheckConstraint("ck_technologies_skill_level", "skill_level IN ('Primary', 'Experienced', 'Familiar', 'Learning')");

                            t.HasCheckConstraint("ck_technologies_years_of_experience", "years_of_experience IS NULL OR years_of_experience >= 0");
                        });
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.TechnologyTranslation", b =>
                {
                    b.Property<Guid>("TechnologyId")
                        .HasColumnType("uuid")
                        .HasColumnName("technology_id");

                    b.Property<string>("LocaleCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("locale_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("TechnologyId", "LocaleCode");

                    b.HasIndex("LocaleCode", "Name")
                        .IsUnique();

                    b.ToTable("technology_translations", null, t =>
                        {
                            t.HasCheckConstraint("ck_technology_translations_locale", "locale_code IN ('en', 'vi')");
                        });
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.WorkExperience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company_name");

                    b.Property<string>("CompanyUrl")
                        .HasColumnType("text")
                        .HasColumnName("company_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<string>("EmploymentType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("employment_type");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_published");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder", "StartDate")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_work_experiences_public_order")
                        .HasFilter("is_published");

                    b.ToTable("work_experiences", null, t =>
                        {
                            t.HasCheckConstraint("ck_work_experiences_dates", "end_date IS NULL OR end_date >= start_date");

                            t.HasCheckConstraint("ck_work_experiences_display_order", "display_order >= 0");
                        });
                });

            modelBuilder.Entity("Portfolio.Infrastructure.Authentication.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Portfolio.Infrastructure.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Portfolio.Infrastructure.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portfolio.Infrastructure.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Portfolio.Infrastructure.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.About", b =>
                {
                    b.HasOne("Portfolio.Application.Common.Models.Profile", "Profile")
                        .WithOne("About")
                        .HasForeignKey("Portfolio.Application.Common.Models.About", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.AboutTranslation", b =>
                {
                    b.HasOne("Portfolio.Application.Common.Models.About", "About")
                        .WithMany("Translations")
                        .HasForeignKey("AboutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("About");
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.CertificateTechnology", b =>
                {
                    b.HasOne("Portfolio.Application.Common.Models.Certificate", "Certificate")
                        .WithMany("Technologies")
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portfolio.Application.Common.Models.Technology", "Technology")
                        .WithMany("Certificates")
                        .HasForeignKey("TechnologyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Certificate");

                    b.Navigation("Technology");
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.CertificateTranslation", b =>
                {
                    b.HasOne("Portfolio.Application.Common.Models.Certificate", "Certificate")
                        .WithMany("Translations")
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Certificate");
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.ExperienceHighlight", b =>
                {
                    b.HasOne("Portfolio.Application.Common.Models.WorkExperience", "Experience")
                        .WithMany("Highlights")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experience");
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.ExperienceTechnology", b =>
                {
                    b.HasOne("Portfolio.Application.Common.Models.WorkExperience", "Experience")
                        .WithMany("Technologies")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portfolio.Application.Common.Models.Technology", "Technology")
                        .WithMany("Experiences")
                        .HasForeignKey("TechnologyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Experience");

                    b.Navigation("Technology");
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.ExperienceTranslation", b =>
                {
                    b.HasOne("Portfolio.Application.Common.Models.WorkExperience", "Experience")
                        .WithMany("Translations")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experience");
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.ProfileTranslation", b =>
                {
                    b.HasOne("Portfolio.Application.Common.Models.Profile", "Profile")
                        .WithMany("Translations")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.ProjectHighlight", b =>
                {
                    b.HasOne("Portfolio.Application.Common.Models.Project", "Project")
                        .WithMany("Highlights")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.ProjectImage", b =>
                {
                    b.HasOne("Portfolio.Application.Common.Models.Project", "Project")
                        .WithMany("Images")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.ProjectImageTranslation", b =>
                {
                    b.HasOne("Portfolio.Application.Common.Models.ProjectImage", "ProjectImage")
                        .WithMany("Translations")
                        .HasForeignKey("ProjectImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectImage");
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.ProjectTechnology", b =>
                {
                    b.HasOne("Portfolio.Application.Common.Models.Project", "Project")
                        .WithMany("Technologies")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portfolio.Application.Common.Models.Technology", "Technology")
                        .WithMany("Projects")
                        .HasForeignKey("TechnologyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Technology");
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.ProjectTranslation", b =>
                {
                    b.HasOne("Portfolio.Application.Common.Models.Project", "Project")
                        .WithMany("Translations")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.ResumeFile", b =>
                {
                    b.HasOne("Portfolio.Application.Common.Models.ResumeVersionCounter", "VersionCounter")
                        .WithMany("Resumes")
                        .HasForeignKey("LanguageCode", "VersionYear")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VersionCounter");
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.ResumeTranslation", b =>
                {
                    b.HasOne("Portfolio.Application.Common.Models.ResumeFile", "Resume")
                        .WithMany("Translations")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.SkillCategoryTranslation", b =>
                {
                    b.HasOne("Portfolio.Application.Common.Models.SkillCategory", "Category")
                        .WithMany("Translations")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.SocialLink", b =>
                {
                    b.HasOne("Portfolio.Application.Common.Models.Profile", "Profile")
                        .WithMany("SocialLinks")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.Technology", b =>
                {
                    b.HasOne("Portfolio.Application.Common.Models.SkillCategory", "Category")
                        .WithMany("Technologies")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.TechnologyTranslation", b =>
                {
                    b.HasOne("Portfolio.Application.Common.Models.Technology", "Technology")
                        .WithMany("Translations")
                        .HasForeignKey("TechnologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Technology");
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.About", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.Certificate", b =>
                {
                    b.Navigation("Technologies");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.Profile", b =>
                {
                    b.Navigation("About");

                    b.Navigation("SocialLinks");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.Project", b =>
                {
                    b.Navigation("Highlights");

                    b.Navigation("Images");

                    b.Navigation("Technologies");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.ProjectImage", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.ResumeFile", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.ResumeVersionCounter", b =>
                {
                    b.Navigation("Resumes");
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.SkillCategory", b =>
                {
                    b.Navigation("Technologies");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.Technology", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("Experiences");

                    b.Navigation("Projects");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Portfolio.Application.Common.Models.WorkExperience", b =>
                {
                    b.Navigation("Highlights");

                    b.Navigation("Technologies");

                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
